import Link from 'next/link'
import './globals.css'
import { LoginCom, LogoutCom } from './LoginCom'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

export const metadata = {
  title: 'Last Dance',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html>
      <body>
        <nav>
          <Link href="/">Home</Link>
          <Link href="/board/list">Board</Link>
          { session ? <LogoutCom/> : <LoginCom/>}
        </nav>
        {children}
      </body>
    </html>
  )
}
